### ISSUE TITLE
Lidar fields - ring

### ISSUE THREAD

**Issue by FedeAi** [FS-Driverless/Formula-Student-Driverless-Simulator#252]
Is there a way to get ring field in lidar pointcloud?

This is a typical velodyne pcl:
```
header: 
  seq: 1071
  stamp: 
    secs: 1521699326
    nsecs: 676390000
  frame_id: "velodyne"
height: 1
width: 66811
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "intensity"
    offset: 16
    datatype: 7
    count: 1
  - 
    name: "ring"
    offset: 20
    datatype: 4
    count: 1
    ...
```

But in the sim both intensity and **ring** are not present.
How can i get the ring field?
